% Taxation in Italy in year 2005

function[inctax,local_tax,socsec,benefit,netincome,netinc_wobenefit,ssc_empr]=tax_it_2005(wage_principal,wage_spouse,married,children)

%************************** EXECUTE THE PARAMETER FUNCTION ************************

[taxbracket1,taxbracket2,taxbracket3,tax_r1,tax_r2,tax_r3,trans_sch_m_thresh1,trans_sch_m_thresh2,trans_sch_m_thresh3,trans_sch_m_thresh4,trans_sch_m_thresh5,trans_sch_m_thresh6,trans_sch_m_thresh7,trans_sch_m_thresh8,trans_sch_m_thresh9,trans_sch_m_thresh10,trans_sch_m_thresh11,trans_sch_m_thresh12,trans_sch_m_thresh13,trans_sch_m_thresh14,trans_sch_m_thresh15,trans_sch_m_thresh16,trans_sch_m1_c1,trans_sch_m2_c1,trans_sch_m3_c1,trans_sch_m4_c1,trans_sch_m5_c1,trans_sch_m6_c1,trans_sch_m7_c1,trans_sch_m8_c1,trans_sch_m9_c1,trans_sch_m10_c1,trans_sch_m11_c1,trans_sch_m12_c1,trans_sch_m13_c1,trans_sch_m14_c1,trans_sch_m15_c1,trans_sch_m1_c2,trans_sch_m2_c2,trans_sch_m3_c2,trans_sch_m4_c2,trans_sch_m5_c2,trans_sch_m6_c2,trans_sch_m7_c2,trans_sch_m8_c2,trans_sch_m9_c2,trans_sch_m10_c2,trans_sch_m11_c2,trans_sch_m12_c2,trans_sch_m13_c2,trans_sch_m14_c2,trans_sch_m15_c2,trans_sch_s_thresh1,trans_sch_s_thresh2,trans_sch_s_thresh3,trans_sch_s_thresh4,trans_sch_s_thresh5,trans_sch_s_thresh6,trans_sch_s_thresh7,trans_sch_s_thresh8,trans_sch_s_thresh9,trans_sch_s_thresh10,trans_sch_s_thresh11,trans_sch_s_thresh12,trans_sch_s_thresh13,trans_sch_s_thresh14,trans_sch_s_thresh15,trans_sch_s_thresh16,trans_sch_s1_c1,trans_sch_s2_c1,trans_sch_s3_c1,trans_sch_s4_c1,trans_sch_s5_c1,trans_sch_s6_c1,trans_sch_s7_c1,trans_sch_s8_c1,trans_sch_s9_c1,trans_sch_s10_c1,trans_sch_s11_c1,trans_sch_s12_c1,trans_sch_s13_c1,trans_sch_s14_c1,trans_sch_s15_c1,trans_sch_s1_c2,trans_sch_s2_c2,trans_sch_s3_c2,trans_sch_s4_c2,trans_sch_s5_c2,trans_sch_s6_c2,trans_sch_s7_c2,trans_sch_s8_c2,trans_sch_s9_c2,trans_sch_s10_c2,trans_sch_s11_c2,trans_sch_s12_c2,trans_sch_s13_c2,trans_sch_s14_c2,trans_sch_s15_c2,trans_sch_s1_c3,trans_sch_s2_c3,trans_sch_s3_c3,trans_sch_s4_c3,trans_sch_s5_c3,trans_sch_s6_c3,trans_sch_s7_c3,trans_sch_s8_c3,trans_sch_s9_c3,trans_sch_s10_c3,trans_sch_s11_c3,trans_sch_s12_c3,trans_sch_s13_c3,trans_sch_s14_c3,trans_sch_s15_c3,sp_crd_lim,s_all,reg_rt,ssc_bracket1,ssc_bracket2,ssc_bracket3,ssc_r1,ssc_r2,ssc_r3,emp_ssc_bracket1,emp_ssc_bracket2,emp_ssc_r1,emp_ssc_r2,b_all,c_all_s1,c_all_s2,c_all_m]=it_parameters_2005;

% ********************************  1) SOCIAL SECURITY CONTRIBUTIONS *****************	
   
[socsec_p,ssc_empr_p] =it_socsec_2006(wage_principal,ssc_bracket1,ssc_bracket2,ssc_bracket3,ssc_r1,ssc_r2,ssc_r3,emp_ssc_bracket1,emp_ssc_bracket2,emp_ssc_r1,emp_ssc_r2);
[socsec_s,ssc_empr_s] =it_socsec_2006(wage_spouse,ssc_bracket1,ssc_bracket2,ssc_bracket3,ssc_r1,ssc_r2,ssc_r3,emp_ssc_bracket1,emp_ssc_bracket2,emp_ssc_r1,emp_ssc_r2);
		
socsec=round(socsec_p+socsec_s);
ssc_empr=round(ssc_empr_p+ssc_empr_s);

%********************************** 2)  TAXABLE INCOME CALCULATION   *********************************************************************************************
 
[taxable_income_p,taxable_income_s,tax_al2_p,tax_al_3_actual_p,tax_al2_s,tax_al_3s_actualtaken]=it_taxableinc_2006(wage_principal,wage_spouse,socsec_p, socsec_s,married, children,b_all,c_all_s1,c_all_s2,c_all_m,sp_crd_lim,s_all,taxbracket1,taxbracket2,taxbracket3);

% ************************** 3) TAXATION ***************************************************************************


[inctax_p,local_tax_p]=it_tax_2005(taxable_income_p,taxbracket1,taxbracket2,taxbracket3,tax_r1,tax_r2,tax_r3,reg_rt,tax_al2_p,tax_al_3_actual_p);
[inctax_s,local_tax_s]=it_tax_2005(taxable_income_s,taxbracket1,taxbracket2,taxbracket3,tax_r1,tax_r2,tax_r3,reg_rt,tax_al2_s,tax_al_3s_actualtaken);
     
inctax=round(inctax_p+inctax_s);
local_tax=round(local_tax_p+local_tax_s);

%******************** 5)BENEFITS*********************************************************************

% Cash Benefit

wage=wage_principal+wage_spouse;

if married==1 &&children==1
    transfer=(wage>trans_sch_m_thresh1 && wage<=trans_sch_m_thresh2)*trans_sch_m1_c1+(wage>trans_sch_m_thresh2 && wage<=trans_sch_m_thresh3)*trans_sch_m2_c1+(wage>trans_sch_m_thresh3 && wage<=trans_sch_m_thresh4)*trans_sch_m3_c1+(wage>trans_sch_m_thresh4 && wage<=trans_sch_m_thresh5)*trans_sch_m4_c1+(wage>trans_sch_m_thresh5 && wage<=trans_sch_m_thresh6)*trans_sch_m5_c1+(wage>trans_sch_m_thresh6 && wage<=trans_sch_m_thresh7)*trans_sch_m6_c1+(wage>trans_sch_m_thresh7 && wage<=trans_sch_m_thresh8)*trans_sch_m7_c1+(wage>trans_sch_m_thresh8 && wage<=trans_sch_m_thresh9)*trans_sch_m8_c1+(wage>trans_sch_m_thresh9 && wage<=trans_sch_m_thresh10)*trans_sch_m9_c1 +(wage>trans_sch_m_thresh10 && wage<=trans_sch_m_thresh11)*trans_sch_m10_c1+(wage>trans_sch_m_thresh11 && wage<=trans_sch_m_thresh12)*trans_sch_m11_c1+(wage>trans_sch_m_thresh12 && wage<=trans_sch_m_thresh13)*trans_sch_m12_c1+(wage>trans_sch_m_thresh13 && wage<=trans_sch_m_thresh14)*trans_sch_m13_c1+(wage>trans_sch_m_thresh14 && wage<=trans_sch_m_thresh15)*trans_sch_m14_c1+(wage>trans_sch_m_thresh15 && wage<=trans_sch_m_thresh16)*trans_sch_m15_c1;
elseif married==1 && children==2
    transfer=(wage>trans_sch_m_thresh1 && wage<=trans_sch_m_thresh2)*trans_sch_m1_c2+(wage>trans_sch_m_thresh2 && wage<=trans_sch_m_thresh3)*trans_sch_m2_c2+(wage>trans_sch_m_thresh3 && wage<=trans_sch_m_thresh4)*trans_sch_m3_c2+(wage>trans_sch_m_thresh4 && wage<=trans_sch_m_thresh5)*trans_sch_m4_c2+(wage>trans_sch_m_thresh5 && wage<=trans_sch_m_thresh6)*trans_sch_m5_c2+(wage>trans_sch_m_thresh6 && wage<=trans_sch_m_thresh7)*trans_sch_m6_c2+(wage>trans_sch_m_thresh7 && wage<=trans_sch_m_thresh8)*trans_sch_m7_c2+(wage>trans_sch_m_thresh8 && wage<=trans_sch_m_thresh9)*trans_sch_m8_c2+(wage>trans_sch_m_thresh9 && wage<=trans_sch_m_thresh10)*trans_sch_m9_c2 +(wage>trans_sch_m_thresh10 && wage<=trans_sch_m_thresh11)*trans_sch_m10_c2+(wage>trans_sch_m_thresh11 && wage<=trans_sch_m_thresh12)*trans_sch_m11_c2+(wage>trans_sch_m_thresh12 && wage<=trans_sch_m_thresh13)*trans_sch_m12_c2+(wage>trans_sch_m_thresh13 && wage<=trans_sch_m_thresh14)*trans_sch_m13_c2+(wage>trans_sch_m_thresh14 && wage<=trans_sch_m_thresh15)*trans_sch_m14_c2+(wage>trans_sch_m_thresh15 && wage<=trans_sch_m_thresh16)*trans_sch_m15_c2;
elseif married==0  && children==1
    transfer=(wage>trans_sch_s_thresh1 && wage<=trans_sch_s_thresh2)*trans_sch_s1_c1+(wage>trans_sch_s_thresh2 && wage<=trans_sch_s_thresh3)*trans_sch_s2_c1+(wage>trans_sch_s_thresh3 && wage<=trans_sch_s_thresh4)*trans_sch_s3_c1+(wage>trans_sch_s_thresh4 && wage<=trans_sch_s_thresh5)*trans_sch_s4_c1+(wage>trans_sch_s_thresh5 && wage<=trans_sch_s_thresh6)*trans_sch_s5_c1+(wage>trans_sch_s_thresh6 && wage<=trans_sch_s_thresh7)*trans_sch_s6_c1+(wage>trans_sch_s_thresh7 && wage<=trans_sch_s_thresh8)*trans_sch_s7_c1+(wage>trans_sch_s_thresh8 && wage<=trans_sch_s_thresh9)*trans_sch_s8_c1+(wage>trans_sch_s_thresh9 && wage<=trans_sch_s_thresh10)*trans_sch_s9_c1 +(wage>trans_sch_s_thresh10 && wage<=trans_sch_s_thresh11)*trans_sch_s10_c1+(wage>trans_sch_s_thresh11 && wage<=trans_sch_s_thresh12)*trans_sch_s11_c1+(wage>trans_sch_s_thresh12 && wage<=trans_sch_s_thresh13)*trans_sch_s12_c1+(wage>trans_sch_s_thresh13 && wage<=trans_sch_s_thresh14)*trans_sch_s13_c1+(wage>trans_sch_s_thresh14 && wage<=trans_sch_s_thresh15)*trans_sch_s14_c1+(wage>trans_sch_s_thresh15 && wage<=trans_sch_s_thresh16)*trans_sch_s15_c1;
elseif married==0  && children==2
    transfer=(wage>trans_sch_s_thresh1 && wage<=trans_sch_s_thresh2)*trans_sch_s1_c2+(wage>trans_sch_s_thresh2 && wage<=trans_sch_s_thresh3)*trans_sch_s2_c2+(wage>trans_sch_s_thresh3 && wage<=trans_sch_s_thresh4)*trans_sch_s3_c2+(wage>trans_sch_s_thresh4 && wage<=trans_sch_s_thresh5)*trans_sch_s4_c2+(wage>trans_sch_s_thresh5 && wage<=trans_sch_s_thresh6)*trans_sch_s5_c2+(wage>trans_sch_s_thresh6 && wage<=trans_sch_s_thresh7)*trans_sch_s6_c2+(wage>trans_sch_s_thresh7 && wage<=trans_sch_s_thresh8)*trans_sch_s7_c2+(wage>trans_sch_s_thresh8 && wage<=trans_sch_s_thresh9)*trans_sch_s8_c2+(wage>trans_sch_s_thresh9 && wage<=trans_sch_s_thresh10)*trans_sch_s9_c2 +(wage>trans_sch_s_thresh10 && wage<=trans_sch_s_thresh11)*trans_sch_s10_c2+(wage>trans_sch_s_thresh11 && wage<=trans_sch_s_thresh12)*trans_sch_s11_c2+(wage>trans_sch_s_thresh12 && wage<=trans_sch_s_thresh13)*trans_sch_s12_c2+(wage>trans_sch_s_thresh13 && wage<=trans_sch_s_thresh14)*trans_sch_s13_c2+(wage>trans_sch_s_thresh14 && wage<=trans_sch_s_thresh15)*trans_sch_s14_c2+(wage>trans_sch_s_thresh15 && wage<=trans_sch_s_thresh16)*trans_sch_s15_c2;
elseif married==0  && children==3
    transfer=(wage>trans_sch_s_thresh1 && wage<=trans_sch_s_thresh2)*trans_sch_s1_c3+(wage>trans_sch_s_thresh2 && wage<=trans_sch_s_thresh3)*trans_sch_s2_c3+(wage>trans_sch_s_thresh3 && wage<=trans_sch_s_thresh4)*trans_sch_s3_c3+(wage>trans_sch_s_thresh4 && wage<=trans_sch_s_thresh5)*trans_sch_s4_c3+(wage>trans_sch_s_thresh5 && wage<=trans_sch_s_thresh6)*trans_sch_s5_c3+(wage>trans_sch_s_thresh6 && wage<=trans_sch_s_thresh7)*trans_sch_s6_c3+(wage>trans_sch_s_thresh7 && wage<=trans_sch_s_thresh8)*trans_sch_s7_c3+(wage>trans_sch_s_thresh8 && wage<=trans_sch_s_thresh9)*trans_sch_s8_c3+(wage>trans_sch_s_thresh9 && wage<=trans_sch_s_thresh10)*trans_sch_s9_c3 +(wage>trans_sch_s_thresh10 && wage<=trans_sch_s_thresh11)*trans_sch_s10_c3+(wage>trans_sch_s_thresh11 && wage<=trans_sch_s_thresh12)*trans_sch_s11_c3+(wage>trans_sch_s_thresh12 && wage<=trans_sch_s_thresh13)*trans_sch_s12_c3+(wage>trans_sch_s_thresh13 && wage<=trans_sch_s_thresh14)*trans_sch_s13_c3+(wage>trans_sch_s_thresh14 && wage<=trans_sch_s_thresh15)*trans_sch_s14_c3+(wage>trans_sch_s_thresh15 && wage<=trans_sch_s_thresh16)*trans_sch_s15_c3;
else
    transfer=0;
end

%no information on (3 or) 4 children in OECD reports, hence I interpolate
%child benefits for more than 2 (3) kids
if married==1 && children>2
    trans1=(wage>trans_sch_m_thresh1 && wage<=trans_sch_m_thresh2)*trans_sch_m1_c1+(wage>trans_sch_m_thresh2 && wage<=trans_sch_m_thresh3)*trans_sch_m2_c1+(wage>trans_sch_m_thresh3 && wage<=trans_sch_m_thresh4)*trans_sch_m3_c1+(wage>trans_sch_m_thresh4 && wage<=trans_sch_m_thresh5)*trans_sch_m4_c1+(wage>trans_sch_m_thresh5 && wage<=trans_sch_m_thresh6)*trans_sch_m5_c1+(wage>trans_sch_m_thresh6 && wage<=trans_sch_m_thresh7)*trans_sch_m6_c1+(wage>trans_sch_m_thresh7 && wage<=trans_sch_m_thresh8)*trans_sch_m7_c1+(wage>trans_sch_m_thresh8 && wage<=trans_sch_m_thresh9)*trans_sch_m8_c1+(wage>trans_sch_m_thresh9 && wage<=trans_sch_m_thresh10)*trans_sch_m9_c1 +(wage>trans_sch_m_thresh10 && wage<=trans_sch_m_thresh11)*trans_sch_m10_c1+(wage>trans_sch_m_thresh11 && wage<=trans_sch_m_thresh12)*trans_sch_m11_c1+(wage>trans_sch_m_thresh12 && wage<=trans_sch_m_thresh13)*trans_sch_m12_c1+(wage>trans_sch_m_thresh13 && wage<=trans_sch_m_thresh14)*trans_sch_m13_c1+(wage>trans_sch_m_thresh14 && wage<=trans_sch_m_thresh15)*trans_sch_m14_c1+(wage>trans_sch_m_thresh15 && wage<=trans_sch_m_thresh16)*trans_sch_m15_c1;
    trans2=(wage>trans_sch_m_thresh1 && wage<=trans_sch_m_thresh2)*trans_sch_m1_c2+(wage>trans_sch_m_thresh2 && wage<=trans_sch_m_thresh3)*trans_sch_m2_c2+(wage>trans_sch_m_thresh3 && wage<=trans_sch_m_thresh4)*trans_sch_m3_c2+(wage>trans_sch_m_thresh4 && wage<=trans_sch_m_thresh5)*trans_sch_m4_c2+(wage>trans_sch_m_thresh5 && wage<=trans_sch_m_thresh6)*trans_sch_m5_c2+(wage>trans_sch_m_thresh6 && wage<=trans_sch_m_thresh7)*trans_sch_m6_c2+(wage>trans_sch_m_thresh7 && wage<=trans_sch_m_thresh8)*trans_sch_m7_c2+(wage>trans_sch_m_thresh8 && wage<=trans_sch_m_thresh9)*trans_sch_m8_c2+(wage>trans_sch_m_thresh9 && wage<=trans_sch_m_thresh10)*trans_sch_m9_c2 +(wage>trans_sch_m_thresh10 && wage<=trans_sch_m_thresh11)*trans_sch_m10_c2+(wage>trans_sch_m_thresh11 && wage<=trans_sch_m_thresh12)*trans_sch_m11_c2+(wage>trans_sch_m_thresh12 && wage<=trans_sch_m_thresh13)*trans_sch_m12_c2+(wage>trans_sch_m_thresh13 && wage<=trans_sch_m_thresh14)*trans_sch_m13_c2+(wage>trans_sch_m_thresh14 && wage<=trans_sch_m_thresh15)*trans_sch_m14_c2+(wage>trans_sch_m_thresh15 && wage<=trans_sch_m_thresh16)*trans_sch_m15_c2;
    transfer=trans2+(trans2-trans1)*(children-2);
elseif married==0  && children>3
    trans1=(wage>trans_sch_s_thresh1 && wage<=trans_sch_s_thresh2)*trans_sch_s1_c2+(wage>trans_sch_s_thresh2 && wage<=trans_sch_s_thresh3)*trans_sch_s2_c2+(wage>trans_sch_s_thresh3 && wage<=trans_sch_s_thresh4)*trans_sch_s3_c2+(wage>trans_sch_s_thresh4 && wage<=trans_sch_s_thresh5)*trans_sch_s4_c2+(wage>trans_sch_s_thresh5 && wage<=trans_sch_s_thresh6)*trans_sch_s5_c2+(wage>trans_sch_s_thresh6 && wage<=trans_sch_s_thresh7)*trans_sch_s6_c2+(wage>trans_sch_s_thresh7 && wage<=trans_sch_s_thresh8)*trans_sch_s7_c2+(wage>trans_sch_s_thresh8 && wage<=trans_sch_s_thresh9)*trans_sch_s8_c2+(wage>trans_sch_s_thresh9 && wage<=trans_sch_s_thresh10)*trans_sch_s9_c2 +(wage>trans_sch_s_thresh10 && wage<=trans_sch_s_thresh11)*trans_sch_s10_c2+(wage>trans_sch_s_thresh11 && wage<=trans_sch_s_thresh12)*trans_sch_s11_c2+(wage>trans_sch_s_thresh12 && wage<=trans_sch_s_thresh13)*trans_sch_s12_c2+(wage>trans_sch_s_thresh13 && wage<=trans_sch_s_thresh14)*trans_sch_s13_c2+(wage>trans_sch_s_thresh14 && wage<=trans_sch_s_thresh15)*trans_sch_s14_c2+(wage>trans_sch_s_thresh15 && wage<=trans_sch_s_thresh16)*trans_sch_s15_c2;
    trans2=(wage>trans_sch_s_thresh1 && wage<=trans_sch_s_thresh2)*trans_sch_s1_c3+(wage>trans_sch_s_thresh2 && wage<=trans_sch_s_thresh3)*trans_sch_s2_c3+(wage>trans_sch_s_thresh3 && wage<=trans_sch_s_thresh4)*trans_sch_s3_c3+(wage>trans_sch_s_thresh4 && wage<=trans_sch_s_thresh5)*trans_sch_s4_c3+(wage>trans_sch_s_thresh5 && wage<=trans_sch_s_thresh6)*trans_sch_s5_c3+(wage>trans_sch_s_thresh6 && wage<=trans_sch_s_thresh7)*trans_sch_s6_c3+(wage>trans_sch_s_thresh7 && wage<=trans_sch_s_thresh8)*trans_sch_s7_c3+(wage>trans_sch_s_thresh8 && wage<=trans_sch_s_thresh9)*trans_sch_s8_c3+(wage>trans_sch_s_thresh9 && wage<=trans_sch_s_thresh10)*trans_sch_s9_c3 +(wage>trans_sch_s_thresh10 && wage<=trans_sch_s_thresh11)*trans_sch_s10_c3+(wage>trans_sch_s_thresh11 && wage<=trans_sch_s_thresh12)*trans_sch_s11_c3+(wage>trans_sch_s_thresh12 && wage<=trans_sch_s_thresh13)*trans_sch_s12_c3+(wage>trans_sch_s_thresh13 && wage<=trans_sch_s_thresh14)*trans_sch_s13_c3+(wage>trans_sch_s_thresh14 && wage<=trans_sch_s_thresh15)*trans_sch_s14_c3+(wage>trans_sch_s_thresh15 && wage<=trans_sch_s_thresh16)*trans_sch_s15_c3;
    transfer=trans2+(trans2-trans1)*(children-3);
end

benefit=round(12*transfer);
        
netincome=wage -inctax-socsec-local_tax+benefit;

netinc_wobenefit=wage -inctax-socsec-local_tax;
end
